spring.application.name=backend-fredo
# PostgreSQL config
spring.datasource.url=jdbc:postgresql://shuttle.proxy.rlwy.net:40402/railway
spring.datasource.username=postgres
spring.datasource.password=cnBOEWYhLcJyHixiTPKCHfDCiLBRKEmd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port
server.port=8080
